services:
  api:
    image: book-finder
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - database

  database:
    image: postgres:alpine
    env_file:
      - path: .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
